// NOTE ADDRESS
export const UPDATE_BILLING_ADDRESS = 'UPDATE_BILLING_ADDRESS';
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';

// NOTE CART
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const EDIT_CART_ITEM = 'EDIT_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECKOUT = 'CHECKOUT';

// NOTE PRODUCTS
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

// NOTE PRODUCT
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_ERROR = 'PRODUCT_FETCH_ERROR';

// NOTE PHOTOS
export const FACEBOOK_FETCH_IMAGES = 'FACEBOOK_FETCH_IMAGES';
export const INSTAGRAM_FETCH_IMAGES = 'INSTAGRAM_FETCH_IMAGES';
export const USERPHOTO_UPLOAD_ERROR = 'USERPHOTO_UPLOAD_ERROR';
export const USERPHOTO_UPLOAD_SUCCESS = 'USERPHOTO_UPLOAD_SUCCESS';
export const SELECTED_PHOTO = 'SELECTED_PHOTO';

// NOTE PROJECT
export const ADD_PHOTO_TO_PROJECT = 'ADD_PHOTO_TO_PROJECT';
export const ADD_EDIT_PHOTO_TO_PROJECT = 'ADD_EDIT_PHOTO_TO_PROJECT';
export const PROJECTS_CLEAR_CURRENT = 'PROJECTS_CLEAR_CURRENT';
export const SET_SELECTED_PHOTO_ID = 'SET_SELECTED_PHOTO_ID';
export const CLEAR_EDIT_PHOTO_TO_PROJECT = 'CLEAR_EDIT_PHOTO_TO_PROJECT';
export const CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT';
export const CLEAR_PROJECT_LIST = 'CLEAR_PROJECT_LIST';

export const ADD_PHOTOS_TO_LIST = 'ADD_PHOTOS_TO_LIST';
export const REMOVE_PHOTO_FROM_LIST = 'REMOVE_PHOTO_FROM_LIST';

// NOTE PROJECT PRODUCT ITEMS
export const ADD_PHOTO_ITEMS_OPTIONS = 'ADD_PHOTO_ITEMS_OPTIONS';
export const EDIT_PHOTO_ITEMS_OPTIONS = 'EDIT_PHOTO_ITEMS_OPTIONS';
export const ADD_ITEMS_QUANTITY = 'ADD_ITEMS_QUANTITY';

// NOTE ORDERS
export const ORDER_PLACE_SUCCESS = 'ORDER_PLACE_SUCCESS';
export const ORDER_PLACE_ERROR = 'ORDER_PLACE_ERROR';

// NOTE TAXES
export const TAXES_FETCH_SUCCESS = 'TAXES_FETCH_SUCCESS';

// NOTE CONFIG
export const SET_CONFIG = 'SET_CONFIG';
export const SET_MULTI_PHOTO = 'SET_MULTI_PHOTO';
export const SET_EXPRESS_MODE = 'SET_EXPRESS_MODE';
